server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true